variables:
    # Configure mysql service (https://hub.docker.com/_/mysql/)
    MYSQL_DATABASE: wordpress_tests
    MYSQL_ROOT_PASSWORD: mysql

stages:
    - verify
    - test
    - release

PHPCS:PHP7.2:
    stage: verify
    image: wpunit/php:wpcs
    script:
        - phpcs
    allow_failure: true

WP-Latest:PHP5.6:
    stage: test
    image: wpunit/php:5.6
    services:
        - mysql:5.6
    script:
        # Set up WordPress tests
        - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql latest true
        - phpunit --configuration phpunit.xml.dist

WP-Latest:PHP7.2:
    stage: test
    image: wpunit/php:7.2
    services:
        - mysql:5.6
    script:
        # Set up WordPress tests
        - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql latest true
        - phpunit --configuration phpunit.xml.dist
    
WP-Latest:PHP7.3:
    stage: test
    image: wpunit/php:7.3
    services:
        - mysql:5.6
    script:
        # Set up WordPress tests
        - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql latest true
        - phpunit --configuration phpunit.xml.dist
    allow_failure: true

WP-Nightly:PHP5.6:
    stage: test
    image: wpunit/php:5.6
    services:
        - mysql:5.6
    script:
        # Set up WordPress tests
        - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql nightly true
        - phpunit --configuration phpunit.xml.dist
    allow_failure: true

WP-Nightly:PHP7.2:
    stage: test
    image: wpunit/php:7.2
    services:
        - mysql:5.6
    script:
        # Set up WordPress tests
        - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql nightly true
        - phpunit --configuration phpunit.xml.dist
    allow_failure: true

WP-Nightly:PHP7.3:
    stage: test
    image: wpunit/php:7.3
    services:
        - mysql:5.6
    script:
        # Set up WordPress tests
        - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql nightly true
        - phpunit --configuration phpunit.xml.dist
    allow_failure: true

WP5.0:PHP7.2:
    stage: test
    image: wpunit/php:7.2
    variables: 
        PHPUNIT_VERSION: 5
    services:
        - mysql:5.6
    script:
        # Set up WordPress tests
        - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql 5.0 true
        - phpunit --configuration phpunit.xml.dist

WP4.9:PHP7.2:
    stage: test
    image: wpunit/php:7.2
    variables: 
        PHPUNIT_VERSION: 5
    services:
        - mysql:5.6
    script:
        # Set up WordPress tests
        - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql 4.9 true
        - phpunit --configuration phpunit.xml.dist

WP4.8:PHP7.2:
    stage: test
    image: wpunit/php:7.2
    variables: 
        PHPUNIT_VERSION: 5
    services:
        - mysql:5.6
    script:
        # Set up WordPress tests
        - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql 4.8 true
        - phpunit --configuration phpunit.xml.dist

WP4.7:PHP7.2:
    stage: test
    image: wpunit/php:7.2
    variables: 
        PHPUNIT_VERSION: 5
    services:
        - mysql:5.6
    script:
        # Set up WordPress tests
        - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql 4.7 true
        - phpunit --configuration phpunit.xml.dist

WP4.6:PHP5.6:
    stage: test
    image: wpunit/php:5.6
    services:
        - mysql:5.6
    script:
        # Set up WordPress tests
        - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql 4.6 true
        - phpunit --configuration phpunit.xml.dist

WP4.5:PHP5.6:
    stage: test
    image: wpunit/php:5.6
    services:
        - mysql:5.6
    script:
        # Set up WordPress tests
        - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql 4.5 true
        - phpunit --configuration phpunit.xml.dist

WP4.4:PHP5.6:
    stage: test
    image: wpunit/php:5.6
    services:
        - mysql:5.6
    script:
        # Set up WordPress tests
        - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql 4.4 true
        - phpunit --configuration phpunit.xml.dist

WP4.3:PHP5.6:
    stage: test
    image: wpunit/php:5.6
    services:
        - mysql:5.6
    script:
        # Set up WordPress tests
        - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql 4.3 true
        - phpunit --configuration phpunit.xml.dist

WP4.2:PHP5.6:
    stage: test
    image: wpunit/php:5.6
    services:
        - mysql:5.6
    script:
        # Set up WordPress tests
        - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql 4.2 true
        - phpunit --configuration phpunit.xml.dist

WP4.1:PHP5.6:
    stage: test
    image: wpunit/php:5.6
    services:
        - mysql:5.6
    script:
        # Set up WordPress tests
        - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql 4.1 true
        - phpunit --configuration phpunit.xml.dist

WP4.0:PHP5.6:
    stage: test
    image: wpunit/php:5.6
    services:
        - mysql:5.6
    script:
        # Set up WordPress tests
        - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql 4.0 true
        - phpunit --configuration phpunit.xml.dist
        - WP_MULTISITE=1 phpunit --configuration phpunit.xml.dist

Release:
    stage: release
    environment: 
        name: release
    image: wpunit/php:svn-release
    when: manual
    script:
        - bash bin/release-wp-plugin.sh
    only:
        - tags