variables:
    # Configure mysql service (https://hub.docker.com/_/mysql/)
    MYSQL_DATABASE: wordpress_tests
    MYSQL_ROOT_PASSWORD: mysql
    MYSQL_USER: mysql

stages:
    - verify
    - test
    - release

# Common before script for all tests
before_script:
    - |
      if [[ ! -z "$WP_VERSION" ]] ; then
          bash bin/install-wp-tests.sh "$MYSQL_DATABASE" "$MYSQL_USER" "$MYSQL_PASSWORD" mysql $WP_VERSION true
          composer global require "phpunit/phpunit=5.7.*"
      fi

# Common script for all tests
script:
    - |
      if [[ ! -z "$WP_VERSION" ]] ; then
          phpunit --configuration phpunit.xml.dist
          WP_MULTISITE=1 phpunit --configuration phpunit.xml.dist
      fi

PHPCS:PHP7.2:
    stage: verify
    image: wpunit/php:wpcs
    script:
        - phpcs
    allow_failure: true

WP-Latest:PHP5.6:
    stage: test
    image: wpunit/php:5.6
    services:
        - mysql:5.6
    variables:
        WP_VERSION: latest

WP-Latest:PHP7.2:
    stage: test
    image: wpunit/php:7.2
    services:
        - mysql:5.6
    variables:
        WP_VERSION: latest
    
WP-Latest:PHP7.3:
    stage: test
    image: wpunit/php:7.3
    services:
        - mysql:5.6
    variables:
        WP_VERSION: latest
    allow_failure: true

WP-Nightly:PHP5.6:
    stage: test
    image: wpunit/php:5.6
    services:
        - mysql:5.6
    variables:
        WP_VERSION: nightly
    allow_failure: true

WP-Nightly:PHP7.2:
    stage: test
    image: wpunit/php:7.2
    services:
        - mysql:5.6
    variables:
        WP_VERSION: nightly
    allow_failure: true

WP-Nightly:PHP7.3:
    stage: test
    image: wpunit/php:7.3
    services:
        - mysql:5.6
    variables:
        WP_VERSION: nightly
    allow_failure: true

WP5.0.3:PHP7.2:
    stage: test
    image: wpunit/php:7.2
    variables: 
        PHPUNIT_VERSION: 5
    services:
        - mysql:5.6
    variables:
        WP_VERSION: 5.0.3

WP4.9.9:PHP7.2:
    stage: test
    image: wpunit/php:7.2
    variables: 
        PHPUNIT_VERSION: 5
    services:
        - mysql:5.6
    variables:
        WP_VERSION: 4.9.9

WP4.8.8:PHP7.2:
    stage: test
    image: wpunit/php:7.2
    variables: 
        PHPUNIT_VERSION: 5
    services:
        - mysql:5.6
    variables:
        WP_VERSION: 4.8.8

WP4.7.12:PHP7.2:
    stage: test
    image: wpunit/php:7.2
    variables: 
        PHPUNIT_VERSION: 5
    services:
        - mysql:5.6
    variables:
        WP_VERSION: 4.7.12

WP4.6.13:PHP5.6:
    stage: test
    image: wpunit/php:5.6
    services:
        - mysql:5.6
    variables:
        WP_VERSION: 4.6.13

WP4.5.16:PHP5.6:
    stage: test
    image: wpunit/php:5.6
    services:
        - mysql:5.6
    variables:
        WP_VERSION: 4.5.16

WP4.4.17:PHP5.6:
    stage: test
    image: wpunit/php:5.6
    services:
        - mysql:5.6
    variables:
        WP_VERSION: 4.4.17

WP4.3.18:PHP5.6:
    stage: test
    image: wpunit/php:5.6
    services:
        - mysql:5.6
    variables:
        WP_VERSION: 4.3.18

WP4.2.22:PHP5.6:
    stage: test
    image: wpunit/php:5.6
    services:
        - mysql:5.6
    variables:
        WP_VERSION: 4.2.22

WP4.1.25:PHP5.6:
    stage: test
    image: wpunit/php:5.6
    services:
        - mysql:5.6
    variables:
        WP_VERSION: 4.1.25

WP4.0.25:PHP5.6:
    stage: test
    image: wpunit/php:5.6
    services:
        - mysql:5.6
    variables:
        WP_VERSION: 4.0.25

Release:
    stage: release
    environment: 
        name: release
    image: wpunit/php:svn-release
    when: manual
    script:
        - bash bin/release-wp-plugin.sh
    only:
        - tags